### ISSUE TITLE
Removing tokens from BPE tokenizer is not supported

### ISSUE THREAD

**Issue by sky-2002** [MinishLab/tokenlearn#13]
Hey @Pringled @stephantul 
I was trying to distill and train the [`answerdotai/ModernBERT-base`](https://huggingface.co/answerdotai/ModernBERT-base) model using `tokenlearn` and getting this error - `Removing tokens from BPE tokenizer is not supported`.
I figured out that because tokens cannot be removed from BPE tokenizer (because BPE tokenizers learn merges between tokens at training time, which effectively “locks in” how tokens can be split or merged), I will need to provide a vocab.
I don't see an option to do it in `train.py`

Also, even if I pass a vocab, I cannot use BPE, as it is not supported yet. 
Can you suggest a workaround, or solution, I can also create a PR if you have some solution in mind, or pls correct me if I am missing something.

I think this is more of a `model2vec` issue, but I came across it when using `tokenlearn`, hence opened here.

**Comment by stephantul** [comment]
Hey @sky-2002!

Thanks for reporting! This has been fixed on main in model2vec. This will no longer crash, but will also not remove the unused tokens. We'll release next week.

I'm closing this, feel free to re-open if necessary. Thanks again!

Stéphan
